version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "openai-qa"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ph3mf5q4s8ba"
s3_prefix = "openai-qa"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=454445151329.dkr.ecr.us-east-1.amazonaws.com/openaiqac6a73d73/inferencefunction7c73919drepo"]
